### ISSUE TITLE
Не понятно как использовать

### ISSUE THREAD

**Issue by des1roer** [vova07/yii2-fileapi-widget#17]
Делаю как в инструкции. Неплохо было бы добавить что в модель нужно добавить preview_url и image_url.
Так вот куда и как сохранить фотки? 
Openserver . сайт localhost\gameproj
в модели

        public function behaviors()
        {
            return [
                'uploadBehavior' => [
                    'class' => UploadBehavior::className(),
                    'attributes' => [
                        'preview_url' => [
                            'path' => 'gameproj/previews',
                            'tempPath' => 'gameproj/temp/files/previews',
                            'url' => 'gameproj/previews'
                        ],
                        'image_url' => [
                            'path' => 'gameproj/images',
                            'tempPath' => 'gameproj/temp/files/images',
                            'url' => 'gameproj/images'
                        ]
                    ]
                ]
            ];
        }

или настройки под линукс и на винде их не повторить?

**Comment by vova07** [comment]
Приветствую!
Почему не повторить, все также только с учетом вашей оси.
Вам нужно указать или абсолютный путь, или алиас директории в атрибутах `path` и `tempPath`.
То как у вас сейчас не годится. 
Должно получится примерно такое:
`C:\Server\gameproj\previews` или `@webroot/previews`

Касательно атрибутов которые нужно добавить. на самом деле их добавлять не нужно, так как можно использовать те которые у вас есть, и те которые нужны вам.

**Comment by des1roer** [comment]
как понимаю нужно указывать путь примерно так Yii::getPathOfAlias('webroot.media').DIRECTORY_SEPARATOR

**Comment by des1roer** [comment]
а вообще на данный момент сделал родными средствами http://yiiframework.ru/forum/viewtopic.php?f=19&t=30550

**Comment by vova07** [comment]
Это виджет для второй версии фрейма.
Но можно не указывать: `Yii::getAlias('@webroot/previews')` а просто `@webroot/previews` так как в самом виджете есть этот вызов алиаса.

**Comment by des1roer** [comment]
а ну да скопировал не из того проекта
$file->saveAs('uploads/' . $file->baseName . '.' . $file->extension);
так в рецепте сохраняют.

**Comment by vova07** [comment]
Разница просто в том что этот виджет делает загрузку асинхронно. Если вас устраивает стандартная форма загрузки, то можно её юзать без проблем.
Если вопрос решён закройте тему пожалуйста!

**Comment by des1roer** [comment]
спасибо за ответы

**Comment by vova07** [comment]
Не за что!
Удачи!
