### ISSUE TITLE
Загрузка php-скрипта

### ISSUE THREAD

**Issue by Mefistophell** [vova07/yii2-fileapi-widget#28]
Здравствуйте! 
Столкнулся с проблемой, когда злоумышленник загрузил php-скрипт в папку с изображениями.
Не знаю, как ему это удалось, но загрузка происходит через fileapi-widget. 
Может быть у вас будут какие-то рекомендации, как защититься от этого. 

Спасибо.

**Comment by vova07** [comment]
Здравстуйте @Mefistophell !
Мое расширение использует стандартный `Yii` валидатор файлов и уже устарелое расширение `FileAPI`, по этому единственное что могу посоветовать это сделать аудит Yii-шного валидатора, и убедится что он не содержит уязвимостей.
К сожалению я давно уже не работаю с Yii, по этому более подробные советы не смогу дать.
С уважением!

**Comment by Mefistophell** [comment]
Благодарю за совет.
